name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      core-changed: ${{ steps.filter.outputs.core }}
      demo-changed: ${{ steps.filter.outputs.demo }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'minecraftlaf/**'
              - 'build.gradle.kts'
              - 'gradle/**'
              - 'settings.gradle.kts'
            demo:
              - 'minecraftlaf-demo/**'
              - 'build.gradle.kts'
              - 'gradle/**'
              - 'settings.gradle.kts'
              - '.github/workflows/*.yml'

  build:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.core-changed == 'true' || needs.determine-changes.outputs.demo-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Debug: locate any wrapper JARs"
        run: |
          echo "Files in gradle/wrapper:"
          find gradle/wrapper -type f || echo "none found"
          echo "Files in root:"
          ls -l gradlew* || echo "none found"


      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build Core
        if: ${{ needs.determine-changes.outputs.core-changed == 'true' }}
        run: ./gradlew :minecraftlaf:build

      - name: Upload Core Artifact
        if: ${{ needs.determine-changes.outputs.core-changed == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: minecraftlaf
          path: minecraftlaf/build/libs/*.jar

      - name: Build Demo
        if: ${{ needs.determine-changes.outputs.demo-changed == 'true' }}
        run: ./gradlew :minecraftlaf-demo:build

      - name: Upload Demo Artifact
        if: ${{ needs.determine-changes.outputs.demo-changed == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: minecraftlaf-demo
          path: minecraftlaf-demo/build/libs/*.jar
